### ISSUE TITLE
Better project icon

### ISSUE THREAD

**Issue by bpepple** [bpepple/bamf#15]
Self explanatory.

**Comment by trumblejoe** [comment]
Here is something I came up with. 
![fcb01811e2e2eeddafb71e12f6f8380f 1](https://user-images.githubusercontent.com/28565202/41446226-52db7ef0-701c-11e8-8680-14f808132abf.png)


ComicStrip Font, Size 65, Blue-Vertical Gradiant, Hexcolor 2A2A57

**Comment by bpepple** [comment]
That looks good, I'll add it to the project later today. Thanks!
