### ISSUE TITLE
Install instrcutions problem on ubuntu 18.04

### ISSUE THREAD

**Issue by tarnecki** [bpepple/bamf#28]
Hi,
having a problem on ubuntu 18.04 with Install Postgresql and Redis - no 3:

**Initialize postgresql:** 

sudo postgresql-setup --initdb --unit postgresql

after running this command sudo asking for password for postgres (which we do not have)

any ideas please?

**Comment by bpepple** [comment]
You probably need to change to the postgres user. Try changing by using: `sudo su - postgres`.

Then try initializing postgresql:
`postgresql-setup --initdb --unit postgresql`

**Comment by tarnecki** [comment]
thats what i did:

postgres@MACHINE:~$ postgresql-setup --initdb --unit postgresql
postgresql-setup: command not found

**Comment by bpepple** [comment]
Alright, let's try this. First, if you are still logged in as the postgres user exit that and go back to your user account.

Ok, now lets see if postgresql is running on your system first by running:

`sudo systemctl status postgresql`

with any luck you'll see it say something like this:

> ● postgresql.service - PostgreSQL RDBMS
        Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
        Active: active (exited) since Sun 2018-05-20 10:04:49 EDT; 1 day 23h ago
    Main PID: 13678 (code=exited, status=0/SUCCESS)
        CGroup: /system.slice/postgresql.service

what we care about is that it says **active**. If it doesn't, run the following:

`sudo systemctl start postgresql`

and then run `sudo systemctl status postgresql` again to verify that it's running.

Provided postgresql is running you should be able to su - back into the postgres user and then go to Step 1, part v.

**Comment by tarnecki** [comment]
so i guess points 3 & 4 are not needed on ubuntu? thanks :)
![image](https://user-images.githubusercontent.com/28607179/40366580-60627b14-5dcf-11e8-84aa-fd9a5ebdc302.png)

**Comment by bpepple** [comment]
Yeah, apparently Ubuntu/Debian must be populating postgresql with initial data during installation.

I'll go ahead and close this bug for now, but feel free to contact me if you have any other problems during installation.

**Comment by tarnecki** [comment]
sorry to reopen:
install bamf section point 4:

![image](https://user-images.githubusercontent.com/28607179/40374131-57799daa-5de0-11e8-8519-b71fe1743745.png)

**Comment by bpepple** [comment]
You need to activate your virtual environment.

`source virt/bin/activate`

**Comment by bpepple** [comment]
Hmm, looks like you've activated your virtual environment based on your screenshot... so, have you installed the dependencies? If not, run (this should be from your virtual environment):
`pip install -r requirements.txt`

**Comment by tarnecki** [comment]
![image](https://user-images.githubusercontent.com/28607179/40376907-7bd9b084-5de7-11e8-979e-c7736ad13b77.png)

**Comment by bpepple** [comment]
The first problem I see is that when you created you virtual environment it was setup up as Python2, not Python3, hence the reason it can't install the latest version of Django (which doesn't support python2). Refer to the Section **Create the Virtual Environment** step **iii**.

Also, you should this in your Home directory, and therefore wouldn't need to be running pip install with sudo (which is due to you not owning the /opt directory).

**Comment by tarnecki** [comment]
i also just notice that my (virt) is on all the time and this is my main setup for websites/other software etc so maybe i need to do the production django version? but how then i can use your  setup?

**Comment by bpepple** [comment]
To turn off the virtual environment you just need to run: `deactivate`.
