### ISSUE TITLE
Comics not importing

### ISSUE THREAD

**Issue by frankenbadger** [bpepple/bamf#30]
Good morning!  I'm having an issue with comics not importing to bamf. It is quite likely user error. I followed the instructions in the wiki to install and bamf seems to be up and running correctly. I have verified that huey, redis, postgres, and of course the server are running. I'm not sure how to attach the log to this post, so i'll include a snippet of it. 
Many thanks for the project. I've been using Tenma for ages and this looks like some pretty great improvments. 

## Expected Behavior
Install bamf. add API key for Comic Vine and comics directory, save. Click import comics. Bamf goes through the process and comics appear. 
## Current Behavior
Install bamf. add API key for Comic Vine and comics directory, save. Click import comics. The log scrolls through about 99 comics and stops. Comics don't appear in the web ui.
## Steps to Reproduce (for bugs)

1. Add API key for Comic Vine and comics directory and save
2. Click import comics

## Your Environment

* Version used: I don't see a version number. I cloned from the repo
* Browser Name and version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 18.04.2 LTS

## Log snippet
`INFO | 03/27/2019 03:04:24 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 03:04:24 AM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 03:04:28 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 03:04:33 AM | basehttp | "GET /publisher/page1/ HTTP/1.1" 200 3718
INFO | 03/27/2019 03:04:34 AM | basehttp | "GET /creator/page1/ HTTP/1.1" 200 3710
INFO | 03/27/2019 03:04:35 AM | basehttp | "GET /character/page1/ HTTP/1.1" 200 3718
INFO | 03/27/2019 03:04:36 AM | basehttp | "GET /team/page1/ HTTP/1.1" 200 3698
INFO | 03/27/2019 03:04:36 AM | basehttp | "GET /arc/page1/ HTTP/1.1" 200 3712
INFO | 03/27/2019 03:04:37 AM | basehttp | "GET /issue/page1/ HTTP/1.1" 200 3439
INFO | 03/27/2019 03:04:39 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 03:04:43 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/css/base.css HTTP/1.1" 200 16225
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/css/responsive.css HTTP/1.1" 200 17976
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO | 03/27/2019 03:04:44 AM | basehttp | "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
WARNING | 03/27/2019 03:04:44 AM | basehttp | "GET /favicon.ico HTTP/1.1" 404 4538
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /admin/star_ratings/rating/add/ HTTP/1.1" 200 6704
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/css/forms.css HTTP/1.1" 200 8505
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/actions.js HTTP/1.1" 200 6538
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/core.js HTTP/1.1" 200 7134
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271751
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/urlify.js HTTP/1.1" 200 8972
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO | 03/27/2019 03:04:49 AM | basehttp | "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
INFO | 03/27/2019 03:05:00 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:05:02 AM | basehttp | "GET /admin/star_ratings/userrating/add/ HTTP/1.1" 200 6646
INFO | 03/27/2019 03:05:03 AM | basehttp | "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO | 03/27/2019 03:05:08 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:05:11 AM | basehttp | "GET /admin/comics/series/add/ HTTP/1.1" 200 5961
INFO | 03/27/2019 03:05:12 AM | basehttp | "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO | 03/27/2019 03:05:18 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:05:22 AM | basehttp | "GET /admin/comics/roles/ HTTP/1.1" 200 5446
INFO | 03/27/2019 03:05:22 AM | basehttp | "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
INFO | 03/27/2019 03:05:22 AM | basehttp | "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO | 03/27/2019 03:05:22 AM | basehttp | "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO | 03/27/2019 03:05:22 AM | basehttp | "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO | 03/27/2019 03:05:25 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:05:27 AM | basehttp | "GET /admin/comics/publisher/ HTTP/1.1" 200 3198
INFO | 03/27/2019 03:05:27 AM | basehttp | "GET /admin/jsi18n/ HTTP/1.1" 200 3185
INFO | 03/27/2019 03:05:31 AM | basehttp | "GET /admin/ HTTP/1.1" 200 7936
INFO | 03/27/2019 03:06:47 AM | basehttp | "GET / HTTP/1.1" 302 0
INFO | 03/27/2019 03:06:47 AM | basehttp | "GET /series/page1/ HTTP/1.1" 302 0
INFO | 03/27/2019 03:06:47 AM | basehttp | "GET /accounts/login/?next=/series/page1/ HTTP/1.1" 200 2572
INFO | 03/27/2019 03:06:52 AM | basehttp | "POST /accounts/login/?next=/series/page1/ HTTP/1.1" 302 0
INFO | 03/27/2019 03:06:52 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 04:22:22 AM | basehttp | "GET /server-settings/ HTTP/1.1" 200 1752
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /importer/ HTTP/1.1" 302 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET / HTTP/1.1" 302 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/css/style.css HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/flexslider/flexslider.css HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/star-ratings/css/star-ratings.css HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/bootstrap/bootstrap.min.js HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/flexslider/jquery.flexslider-min.js HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/js/script.js HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/star-ratings/js/dist/star-ratings.min.js HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:25 AM | basehttp | "GET /static/site/img/comicvine_logo.png HTTP/1.1" 304 0
INFO | 03/27/2019 04:22:28 AM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 04:22:29 AM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 0 /home/brian/Comics/1602 Witch Hunter Angela (2015)/1602 Witch Hunter Angela - #002 (2015).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 1 /home/brian/Comics/1602 Witch Hunter Angela (2015)/1602 Witch Hunter Angela - #003 (2015).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 2 /home/brian/Comics/Commies from Mars The Red Planet (1973)/Commies from Mars The Red Planet - #001 (1973).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 3 /home/brian/Comics/Commies from Mars The Red Planet (1973)/Commies from Mars The Red Planet - #003 (1981).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 4 /home/brian/Comics/Commies from Mars The Red Planet (1973)/Commies from Mars The Red Planet - #005 (0000).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 5 /home/brian/Comics/Commies from Mars The Red Planet (1973)/Commies from Mars The Red Planet - #002 (1979).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 6 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #631 (2004).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 7 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #565 (1999).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 8 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #567 (1999).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 9 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #641 (2005).cbz
INFO | 03/27/2019 04:22:30 AM | comicimporter | Reading in 10 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #642 (2005).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 11 /home/brian/Comics/A Walk Through Hell (2018)/A Walk Through Hell - #001 (2018).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 12 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #604 (2002).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 13 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #562 (1998).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 14 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #523 (1995).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 15 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #442 (1988).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 16 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #563 (1998).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 17 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #1000000 (1998).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 18 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #640 (2005).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 19 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #643 (2005).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 20 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #566 (1999).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 21 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #564 (1999).cbz
INFO | 03/27/2019 04:22:31 AM | comicimporter | Reading in 22 /home/brian/Comics/Adventures of Superman (1987)/Adventures of Superman - #524 (1995).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 23 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #001 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 24 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #002 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 25 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #003 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 26 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #004 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 27 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #006 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 28 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #007 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 29 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #008 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 30 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #010 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 31 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #011 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 32 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #012 (2018).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 33 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #013 (2019).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 34 /home/brian/Comics/Dark Ark (2017)/Dark Ark - #014 (2019).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 35 /home/brian/Comics/Deadpool (2008)/Deadpool - #900 (2009).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 36 /home/brian/Comics/Deadpool (2015)/Deadpool - #023 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 37 /home/brian/Comics/Deadpool (2008)/Deadpool - #020 (2010).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 38 /home/brian/Comics/Deadpool (1997)/Deadpool - #033 (1999).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 39 /home/brian/Comics/Deadpool (1997)/Deadpool - #006 (1997).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 40 /home/brian/Comics/Deadpool (2008)/Deadpool - #021 (2010).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 41 /home/brian/Comics/Deadpool (2008)/Deadpool - #032 (2011).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 42 /home/brian/Comics/Deadpool (2008)/Deadpool - #015 (2009).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 43 /home/brian/Comics/Deadpool (2008)/Deadpool - #012 (2009).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 44 /home/brian/Comics/Deadpool (2008)/Deadpool - #011 (2009).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 45 /home/brian/Comics/Deadpool (2008)/Deadpool - #046 (2012).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 46 /home/brian/Comics/Deadpool (2008)/Deadpool - #023 (2010).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 47 /home/brian/Comics/Deadpool (2008)/Deadpool - #060 (2012).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 48 /home/brian/Comics/Deadpool (2008)/Deadpool - #052 (2012).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 49 /home/brian/Comics/Deadpool (2008)/Deadpool - #028 (2010).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 50 /home/brian/Comics/Deadpool (1997)/Deadpool - #049 (2001).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 51 /home/brian/Comics/Deadpool (1997)/Deadpool - #034 (1999).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 52 /home/brian/Comics/Deadpool (2015)/Deadpool - #030 (2017).cbz
INFO | 03/27/2019 04:22:32 AM | comicimporter | Reading in 53 /home/brian/Comics/Deadpool (1997)/Deadpool - #047 (2000).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 54 /home/brian/Comics/Deadpool (2008)/Deadpool - #008 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 55 /home/brian/Comics/Deadpool (1997)/Deadpool - #051 (2001).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 56 /home/brian/Comics/Deadpool (2012)/Deadpool - #020 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 57 /home/brian/Comics/Deadpool (2008)/Deadpool - #038 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 58 /home/brian/Comics/Deadpool (2008)/Deadpool - #004 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 59 /home/brian/Comics/Deadpool (1997)/Deadpool - #048 (2001).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 60 /home/brian/Comics/Deadpool (2008)/Deadpool - #026 (2010).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 61 /home/brian/Comics/Deadpool (2008)/Deadpool - #010 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 62 /home/brian/Comics/Deadpool (1997)/Deadpool - #062 (2002).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 63 /home/brian/Comics/Deadpool (2008)/Deadpool - #007 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 64 /home/brian/Comics/Deadpool (2015)/Deadpool - #028 (2017).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 65 /home/brian/Comics/Deadpool (2015)/Deadpool - #029 (2017).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 66 /home/brian/Comics/Deadpool (2008)/Deadpool - #013 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 67 /home/brian/Comics/Deadpool (2008)/Deadpool - #053 (2012).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 68 /home/brian/Comics/Deadpool (1997)/Deadpool - #046 (2000).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 69 /home/brian/Comics/Deadpool (1997)/Deadpool - #066 (2002).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 70 /home/brian/Comics/Deadpool (1997)/Deadpool - #032 (1999).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 71 /home/brian/Comics/Deadpool (2012)/Deadpool - #024 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 72 /home/brian/Comics/Deadpool (1997)/Deadpool - #063 (2002).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 73 /home/brian/Comics/Deadpool (2012)/Deadpool - #023 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 74 /home/brian/Comics/Deadpool (2008)/Deadpool - #061 (2012).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 75 /home/brian/Comics/Deadpool (2008)/Deadpool - #059 (2012).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 76 /home/brian/Comics/Deadpool (2008)/Deadpool - #003 (2008).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 77 /home/brian/Comics/Deadpool (1997)/Deadpool - #031 (1999).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 78 /home/brian/Comics/Deadpool (2008)/Deadpool - #044 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 79 /home/brian/Comics/Deadpool (1997)/Deadpool - #009 (1997).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 80 /home/brian/Comics/Deadpool (1997)/Deadpool - #064 (2002).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 81 /home/brian/Comics/Deadpool (2008)/Deadpool - #033.1 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 82 /home/brian/Comics/Deadpool (1997)/Deadpool - #001 (1997).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 83 /home/brian/Comics/Deadpool (2012)/Deadpool - #029 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 84 /home/brian/Comics/Deadpool (2008)/Deadpool - #036 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 85 /home/brian/Comics/Deadpool (2008)/Deadpool - #033 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 86 /home/brian/Comics/Deadpool (1997)/Deadpool - #004 (1997).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 87 /home/brian/Comics/Deadpool (2012)/Deadpool - #021 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 88 /home/brian/Comics/Deadpool (2015)/Deadpool - #036 (2017).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 89 /home/brian/Comics/Deadpool (2015)/Deadpool - #032 (2017).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 90 /home/brian/Comics/Deadpool (2012)/Deadpool - #036 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 91 /home/brian/Comics/Deadpool (1997)/Deadpool - #007 (1997).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 92 /home/brian/Comics/Deadpool (2012)/Deadpool - #019 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 93 /home/brian/Comics/Deadpool (1997)/Deadpool - #005 (1997).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 94 /home/brian/Comics/Deadpool (2012)/Deadpool - #011 (2013).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 95 /home/brian/Comics/Deadpool (2012)/Deadpool - #033 (2014).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 96 /home/brian/Comics/Deadpool (2008)/Deadpool - #005 (2009).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 97 /home/brian/Comics/Deadpool (2008)/Deadpool - #035 (2011).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 98 /home/brian/Comics/Deadpool (1997)/Deadpool - #067 (2002).cbz
INFO | 03/27/2019 04:22:33 AM | comicimporter | Reading in 99 /home/brian/Comics/Deadpool (2008)/Deadpool - #002 (2008).cbz
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/flexslider/flexslider.css HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/star-ratings/css/star-ratings.css HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/css/style.css HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/bootstrap/bootstrap.min.js HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/flexslider/jquery.flexslider-min.js HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/js/script.js HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/star-ratings/js/dist/star-ratings.min.js HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:27 PM | basehttp | "GET /static/site/img/comicvine_logo.png HTTP/1.1" 304 0
INFO | 03/27/2019 12:48:28 PM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 12:48:29 PM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 12:48:30 PM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 12:48:30 PM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 12:48:31 PM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 12:48:31 PM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 12:48:32 PM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 12:48:32 PM | basehttp | "GET /series/page1/ HTTP/1.1" 200 3680
INFO | 03/27/2019 12:48:33 PM | basehttp | "GET /static/site/img/logo.png HTTP/1.1" 200 3490
INFO | 03/27/2019 12:51:44 PM | basehttp | "GET /server-settings/ HTTP/1.1" 200 1752
`

**Comment by bpepple** [comment]
Let's start off with a simple question right off the bat to try to narrow down the bug. Does your comic archive (.cbz) have a ComicInfo.xml file in it with data from Comic Vine? If it does, have you verified your Comic Vine api key? And finally, I believe you can just drag & drop you log file(which should be in the log directory in Bamf) into a comment on this bug.

**Comment by frankenbadger** [comment]
Ok, lets see here.  
I reinstalled everything from scratch just to make sure that I didn't miss something. 
I went through and spot checked both cbr and cbz archives.  I did find a couple that do not have the ComicInfo.xml file, but the vast majority of them do. 
This is the contents of one of those files:

```
<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Series>Batman Beyond</Series>
  <Number>029</Number>
  <Web>https://www.comixology.com/Batman-Beyond-2016-29/digital-comic/755676</Web>
  <Volume>2016</Volume>
  <Summary>The Joker is prepared to deliver his fatal punchline as everything—and the kitchen sink, too—hits the fan for Batman and Robin. Even with Dick Grayson’s help, the Dynamic Duo of tomorrow and Bruce Wayne may not stand a chance. Will The Joker turn Terry’s brother into the new Jason Todd? Is now a good time for Terry and Bruce to clash? And why are Neo-Gothamites cheering on the Clown Prince? Will anyone survive “The Final Joke”?</Summary>
  <Notes>Scraped metadata from Comixology [CMXDB755676], [RELDATE:2019-02-27]</Notes>
  <Publisher>DC</Publisher>
  <Genre>Superhero</Genre>
  <PageCount>25</PageCount>
  <LanguageISO>en</LanguageISO>
  <ScanInformation></ScanInformation>
</ComicInfo>
```
I see comixology in there vs comicvine. Not sure how many of them are like that. I've been using mylar to sort and write metadata. Looking back through that I see that I have a box checked to "Write ComicRack (cr) tags (ComicInfo.xml)". Mylar is also using my Comicvine API key.

I verified my API key in both bamf and mylar with comicvine. So that part looks good. 

[bamf.log](https://github.com/bpepple/bamf/files/3022742/bamf.log)

**Comment by bpepple** [comment]
Ok, the comic archive using Comixology for the metadata would _definitely_ be the problem, since I'm using ComicVine for data retrieval. Never used Mylar, but to import those files, they need to be retagged with Comic Vine data.

**Comment by frankenbadger** [comment]
Sounds good. I'm gonna start googling a good way to do this. Any tips? 
Thanks again for the help. I'm pretty excited about bamf.

**Comment by bpepple** [comment]
You might try [ComicTagger](https://github.com/davide-romanini/comictagger), though I'm sure where they are in their rewrite to Python3.

**Comment by frankenbadger** [comment]
Was just reading about that on reddit. 
Thanks again Mr. Pepple!

**Comment by frankenbadger** [comment]
Looks like tagging did it. Mylar uses comic tagger also, so i'm not sure what the difference is, but I'm going to see if i can figure that part out. 
Thanks again for your time and effort. I really appreciate it!

**Comment by bpepple** [comment]
You might check to see if the files you downloaded already had existing tags and Mylar just skipped them. Anyway, I'll go ahead and close this bug then.
